### ISSUE TITLE
Problems Installing FeynCalc 9.0.0 with Mathematica 10.0.1.0

### ISSUE THREAD

**Issue by fliptanedo** [FeynCalc/feyncalc#1]
I've downloaded FeynCalc and placed it into a separate folder. My attempt to load the package, however, fails as follows:

![screen shot 2015-01-08 at 12 33 28 pm](https://cloud.githubusercontent.com/assets/10454879/5670198/b3b8bbaa-9732-11e4-9e56-1da135eee8c2.png)

I'm using Mathematica 10.0.1.0 on OS X 10.10.1.

In the meanwhile I'm using FeynCalc 8.2.0, installed with the command `Import["http://www.feyncalc.org/install.m"]`.

**Comment by vsht** [comment]
I don't quite understand, why you put FeynCalc into the Documents folder, instead of 
FileNameJoin[{$UserBaseDirectory, "Applications"}]?

Did you read the installation guide on the wiki:
https://github.com/FeynCalc/feyncalc/wiki/Installation

BTW, the development version can be installed via the Import command as well
`Import["http://users.ph.tum.de/ga57tah/feyncalc/FeynCalcInstallNightly.m"]`
which is of course also mentioned on the wiki.

**Comment by fliptanedo** [comment]
Ah! Thank you for clarifying this. I was following the instructions in the FeynCalc guide:

![screen shot 2015-01-09 at 10 40 07 am](https://cloud.githubusercontent.com/assets/10454879/5685104/f3e64a3a-97eb-11e4-82b9-c5f82fbc798b.png)

So I thought I could install into a separate path that's not inside the Mathematica directory. Thanks for explaining! So the 8.2.0 version that I grabbed using the Import command is the latest stable version?

**Comment by fliptanedo** [comment]
Hello, I have one follow up question. 

After running `Import["http://www.feyncalc.org/install.m"]`, FeynCalc 8.2.0 is downloaded and loaded and seems to work fine. After quitting the Mathematica kernel (or restarting Mathematica), I then attempt to load FeynCalc using `Import["http://www.feyncalc.org/install.m"]`, but now I get a series of error/warning messages:

![screen shot 2015-01-09 at 11 13 19 am](https://cloud.githubusercontent.com/assets/10454879/5685691/a141482e-97f1-11e4-922c-d1f35eebf456.png)

FeynCalc appears to be working properly despite the multiple messages, but I wanted to check if this is normal. I'm on Mathematica 10.0.1.0 on OS X 10.10.1

**Comment by vsht** [comment]
Interesting. Actually on Fedora I ineed can load the latest development snapshot from any directory, e.g. 
```<< "/home/vs/Downloads/feyncalc-master/FeynCalc/FeynCalc.m"```
So this seems to be some OS X related issue...

And yes FeynCalc 8.2 is the latest stable release, while the master branch of our Git repo is unstable/testing.

As far as the second issue is concerned, you need to patch FeynArts to work with FeynCalc, see:
https://github.com/FeynCalc/feyncalc/wiki/FeynArts#patching_fa
If you don't plan to use FeynArts anyhow, then it is sufficient to ```$LoadFeynArts = False;``` before loading FeynCalc.

**Comment by fliptanedo** [comment]
Thanks!

**Comment by vsht** [comment]
Could you please try this (i.e. loading from an arbitrary directory on OSX) again with the latest commit?
I think that now it should work.

**Comment by vsht** [comment]
Ok, since there seem to be no further complaints, I'm closing the issue. Feel free to reopen it if there are still any problems loading FeynCalc from an arbitrary directory on Linux, OS X or Windows.
