### ISSUE TITLE
Problem on loading Feynart

### ISSUE THREAD

**Issue by javadebadi** [FeynCalc/feyncalc#12]
I've installed FeynCalc and FeynArt using online installation, in mathematica 10.3. 
I opened the file "QEDElectronMuonScatteringTree" from the "example" folder in FeynCalc folder. Howerver, when the code reached to "Generate Feynman diagrams" I got this error:
 --------------------------------------------------------------------------------------
ln[7]:= topElMuScat = CreateTopologies[0, 2 -> 2];
diagsElMuScat = InsertFields[topElMuScat, {F[2, {1}], F[2, {2}]} ->
		{F[2, {1}], F[2, {2}]}, InsertionLevel -> {Classes},
		Model -> "SM", ExcludeParticles -> {S[1], S[2], V[2]}];
Paint[diagsElMuScat, ColumnsXRows -> {1, 1}, Numbering -> None,SheetHeader->None,ImageSize->{256,256}];

During evaluation of In[7]:= TagSetDelayed::tagnf: Tag FourVector not found in -Overscript[mom_, _]^mu___. >>

Out[8]= $Aborted
--------------------------------------------------------------------------------------
I don't know if it is a problem related to Mathematica or FeynCalc.

**Comment by vsht** [comment]
To me it looks very much like FeynArts was not patched. What is exact the output of

```
$LoadFeynArts = True;
<< FeynCalc`
```


Did you agree when the installer asked you, if FeynArts should be patched for FeynCalc?

Cheers,
Vladyslav

**Comment by javadebadi** [comment]
Yes. I agreed when the installer asked me for FeynArts patching for FeynCalc.
The input and ouput of the code you have written is:

$LoadFeynArts = True;
<< FeynCalc`
FeynCalc 9.0.1. For help, use the documentation center, check out the wiki or write to the mailing list.
FeynArts 3.9 patched for use with FeynCalc, for documentation use the manual or visit www.feynarts.de.


![new bitmap image](https://cloud.githubusercontent.com/assets/21107499/17830659/fe0a3726-66e6-11e6-9cd8-10f1be5353a2.png)

I think the problem is with my mathematica. I will reinstall Mathematica and if problem remains I will inform.

Thank you,
Javad

**Comment by javadebadi** [comment]
The problem is solved. Before I install FeynCalc online, first I had tried to install FeynCalc manually, and I had copied some files of FeynArt in this address
C:/Usesrs/Javad2/Doucments/Model
I deleted these files, in addition reinstalled the Mathematica, now everything is fine.

Sincerely,
Javad
