### ISSUE TITLE
Automatic installation of development version fails

### ISSUE THREAD

**Issue by kenmimasu** [FeynCalc/feyncalc#120]
*  <summary>Your Mathematica version</summary>    

  ```12.1.1 for Mac OS X x86 (64-bit) (June 19, 2020)```

*  <summary>Your FeynCalc version</summary>    

  ```N/A```

*  <summary>Did you try to reinstall FeynCalc (stable version) using the automatic installer to make sure that you have the latest bugfixes?</summary>    

  ```No```

*  <summary>Does your Mathematica initialization file contain statements that might influence the behavior of FeynCalc? Sometimes external packages may modify `init.m` in unusual ways, causing troubles for other codes.</summary>    

  ```$Path = Join[{ToFileName[$HomeDirectory, "Work/apps/Mathematica/LoopTools/x86_64-Darwin/bin"]}, $Path]``` 

*  <summary>Please provide a minimal working example that illustrates the problem and works on a fresh kernel. The example should be provided either by writing the code (as `InputForm`!) directly in the issue text  or by attaching a Mathematica notebook. Please do not post code samples as screenshots, PDF files etc.: Those essentially require us to retype everything by hand, which is annoying and also time consuming. Please explain the difference between the current behavior and the expected behavior.</summary>    

Issue: The automatic installer of the development version is failing as shown below. Stable version installs without issue.

```
Import["https://raw.githubusercontent.com/FeynCalc/feyncalc/master/install.m"]
InstallFeynCalc[InstallFeynCalcDevelopmentVersion -> True]
```

Output:  
```
Downloading FeynCalc from https://github.com/FeynCalc/feyncalc/archive/master.zip ...done! 
FeynCalc zip file was saved to /private/var/folders/30/81kkryrd0cv75k5_2jtzk79w0000gn/T/m000005161721.
Extracting FeynCalc zip file to /private/var/folders/30/81kkryrd0cv75k5_2jtzk79w0000gn/T/m000005161721.dir ...done! 
Checking the directory structure...
Failed to recognize the directory structure of the downloaded zip file. 
Installation aborted!
```

**Comment by vsht** [comment]
Thanks. Indeed this issue was not there before I introduced the new .m-formatted documentation.

With the fix I just pushed to the repo the installer now works for me. Does this solve the problem for you too?

**Comment by kenmimasu** [comment]
Yes it works for me now, thanks!

**Comment by vsht** [comment]
Thanks for the prompt feedback.
