### ISSUE TITLE
Explicit SU(3) calculation

### ISSUE THREAD

**Issue by Mantani** [FeynCalc/feyncalc#14]
Hi,
Is it possible to do explicit SU(3) calculation with Feyncalc? I can only obtain result depending on N, CA e CF and i can't substitute them with their value for N=3.
Thanks for the help,
Luca

**Comment by vsht** [comment]
Yes, by using the option SUNNToCACF. See

https://feyncalc.github.io/FeynCalcBook/ref/SUNSimplify.html

Cheers,
Vladyslav

Am 12.10.2016 um 10:23 schrieb Mantani:

**Comment by Mantani** [comment]
Ok, great! But i'm still not able to set N=3, isn't there an option to do it?
Cheers
Luca

**Comment by vsht** [comment]
It is not an N, it is a SUNN:

```
    ex = SUNSimplify[SUNT[a, b, a, b], SUNNToCACF -> False]
    ex // InputForm
```

Hence, `ex /. SUNN -> 3`

Cheers,
Vladyslav

Am 12.10.2016 um 15:09 schrieb Mantani:

**Comment by Mantani** [comment]
Perfect!
Luca
