### ISSUE TITLE
FCFADiracChainJoin failed with `Evaluation of isolated objects failed` error

### ISSUE THREAD

**Issue by Turgon-Aran-Gondolin** [FeynCalc/feyncalc#143]
*  <summary>Your Mathematica version</summary>    

  ```12.3.1 for Linux x86 (64-bit) (June 24, 2021)```

*  <summary>Your FeynCalc version</summary>    

  ```9.3.1```

*  <summary>Did you try to reinstall FeynCalc (stable version) using the automatic installer to make sure that you have the latest bugfixes?</summary>    

  ```No, but this version should be up-to-date with the hot-fix-stable branch```

*  <summary>Does your Mathematica initialization file contain statements that might influence the behavior of FeynCalc? Sometimes external packages may modify `init.m` in unusual ways, causing troubles for other codes.</summary>    

  ```No``` 

*  <summary>Please provide a minimal working example that illustrates the problem and works on a fresh kernel. The example should be provided either by writing the code (as `InputForm`!) directly in the issue text  or by attaching a Mathematica notebook. Please do not post code samples as screenshots, PDF files etc.: Those essentially require us to retype everything by hand, which is annoying and also time consuming. Please explain the difference between the current behavior and the expected behavior.</summary>    

```
    { DiracChain[Spinor[-Momentum[InMom1], mqu, 1], 
    DiracIndex[Dir1]] DiracChain[Spinor[-Momentum[InMom2], mqu, 1], 
    DiracIndex[Dir2]] DiracChain[
    mqu + DiracGamma[Momentum[InMom2 - OutMom3]], DiracIndex[Dir5], 
    DiracIndex[Dir6]] DiracChain[
    DiracGamma[Momentum[-OutMom1 - OutMom2]] . 
     DiracGamma[LorentzIndex[Lor2]] . DiracGamma[7], DiracIndex[Dir5],
     DiracIndex[Dir1]] DiracChain[
    DiracGamma[LorentzIndex[Lor1]] . DiracGamma[7], DiracIndex[Dir2], 
    DiracIndex[Dir6]]} // FCFADiracChainJoin
```
This will produce a `Error! FCFADiracChainJoin has encountered a fatal problem and must abort the computation. The problem reads: "Evaluation of isolated objects failed."`. However, reduce the number of gamma matrice in the block `(Dir5,Dir1)` will produce a result： 
``` 
   { DiracChain[Spinor[-Momentum[InMom1], mqu, 1], 
    DiracIndex[Dir1]] DiracChain[Spinor[-Momentum[InMom2], mqu, 1], 
    DiracIndex[Dir2]] DiracChain[
    mqu + DiracGamma[Momentum[InMom2 - OutMom3]], DiracIndex[Dir5], 
    DiracIndex[Dir6]] DiracChain[
    DiracGamma[LorentzIndex[Lor2]] . DiracGamma[7], DiracIndex[Dir5], 
    DiracIndex[Dir1]] DiracChain[
    DiracGamma[LorentzIndex[Lor1]] . DiracGamma[7], DiracIndex[Dir2], 
    DiracIndex[Dir6]]} // FCFADiracChainJoin
```

**Comment by vsht** [comment]
Thanks for the bug report. This should be now fixed.

**Comment by Turgon-Aran-Gondolin** [comment]
Thanks! It works for me now.

**Comment by vsht** [comment]
Thanks for the feedback.
