### ISSUE TITLE
Feature request: Choose different basis for `SetMandelstam` 

### ISSUE THREAD

**Issue by Turgon-Aran-Gondolin** [FeynCalc/feyncalc#145]
When using `SetMandelstam` for 5-point amplitude, the default basis of Mandelstam variables is `{s12, s15, s34, s23, s45}`. It would be great if an option is added to choose the basis manually.

**Comment by vsht** [comment]
Choosing the basis manually implies that there should be a list of bases to choose from,
if I understand your proposal correctly? Then one should ask what bases are generic enough
to be useful for most people.

Personally, I would prefer to set the variables directly via SP/SPD to have what I need.

**Comment by vsht** [comment]
@Turgon-Aran-Gondolin So to come back to my original question: Which parametrizations do you precisely have in mind?

**Comment by vsht** [comment]
I guess it makes no sense to keep this issue open, since the reporter doesn't seem to be interested anymore.
