### ISSUE TITLE
explicit component of a FourVector

### ISSUE THREAD

**Issue by ricos92** [FeynCalc/feyncalc#15]
Is there a way to explicitly define the components of a FourVector? 
For example, I wanted to create a fourvector p=(0,1,0,0). I naively tried something like:
FV[p,mu];
p[0]=0;
p[1]=1;
p[2]=0;
p[3]=0;

and than tried to evaluate SP[p,p] expecting "-1" but instead the output was "p^2". How can I define an explicit FV that works in all other FV-related functions?

**Comment by vsht** [comment]
There is no easy way for that. You can replace your scalar products with
whatever you want, e.g.

FV[a, mu] FV[b, mu] // Contract
% /. {FCI[SP[a, b]] -> 1}

But it is not possible to define single components in advance such that
it would work with the internal functions.

Cheers,
Vladyslav


Am 13.10.2016 um 10:57 schrieb ricos92:

**Comment by ricos92** [comment]
Hi,


ok, so is there a way to compute amplitudes with defined helicity states instead of summing over all polarizations?

Thanks


Riccardo

________________________________
Da: Vladyslav Shtabovenko <notifications@github.com>
Inviato: lunedì 17 ottobre 2016 20.55.11
A: FeynCalc/feyncalc
Cc: Riccardo Costa; Author
Oggetto: Re: [FeynCalc/feyncalc] explicit component of a FourVector (#15)


Closed #15<https://github.com/FeynCalc/feyncalc/issues/15>.

-

**Comment by vsht** [comment]
In general, you can always construct manifestly Lorentz covariant expressions for polarization vectors
and spinors that denote a particular polarization/helicity. However, depending on the frame and the number of particles, one might need to think a bit.

For fermions a good example is given in Peskin, Chapter 5.2. For vector bosons see e.g. p.96 in arXiv:hep-ph/9507456.
