### ISSUE TITLE
bug(?) for DiracTrace when color matrices involved

### ISSUE THREAD

**Issue by QSSRHelper** [FeynCalc/feyncalc#168]
```12.1.1 Windows11 ```

  ```9.3.1```

  ```No```

  ```(** User Mathematica initialization file **)``` 

*  The DiracTrace works not properly when color matrices are involved, although it can be avoided by evaluating SUNTrace first.   

  ```
tmp = MTD[lord, lorf] MTD[lorc, lore] SUNF[cola, colb, colc] GAD[\[Mu]].GA[5].SUNT[a].(SUNT[cola,colb].GAD[lorc].GSD[x].GAD[lord]).GAD[\[Nu]].GA[5].(SUNT[colc].GAD[lore, lorf].GSD[x] + SUNT[colc].FVD[x, lore].GAD[lorf]);
tmp // TR // SUNTrace // SUNSimplify
tmp // SUNTrace // TR // SUNSimplify
```

* The T^colc not stay in dot produce after DiracTrace.
```
tmp // TR
```

*  (This is how previous issue "https://github.com/FeynCalc/feyncalc/issues/161" originated. I haven't located the problem correctly ...)

**Comment by vsht** [comment]
Thanks for the clear problem description. This is indeed a bug in a core function (`DotSimplify`)
and a very nasty one. I wonder why it didn't show up earlier.

Anyway, it should be now fixed. Please check if the fix covers all your relevant cases.
