### ISSUE TITLE
Problem with Contract[exp1,exp2]

### ISSUE THREAD

**Issue by kirtimaan** [FeynCalc/feyncalc#17]
![screenshot from 2016-11-21 14-15-02](https://cloud.githubusercontent.com/assets/14826608/20496940/3ddfefa6-aff5-11e6-84d7-616926125ab8.png)

Screen shot of mathematica notebook showing the problem with Contract.

Contract[exp1,exp2] != Contract[exp2,exp1]

**Comment by vsht** [comment]
You are using wrong syntax. `Contract[exp1,exp2]` is meant for internal use only, not for end-users.
 What you should use is `Contract[expr,]`, e.g.
```
Contract[(MT[a, b] FV[p, mu] FVD[q, nu] +  MT[mu, nu] FV[p, a] FV[q, b]) MT[mu, nu]]
Contract[(MT[a, b] FV[p, mu] FVD[q, nu] +  MT[mu, nu] FV[p, a] FV[q, b]) MT[a, b]]
```
See also  https://feyncalc.github.io/FeynCalcBook/ref/Contract.html

**Comment by kirtimaan** [comment]
Thanks,
This should be updated in the FeynCalc reference which states the following
"Contract[exp1, exp2] contracts (exp1*exp2), where exp1 and exp2 may be larger products of sums of metric tensors and 4-vectors."
--https://feyncalc.org/FeynCalcBook/Contract/index.html

**Comment by vsht** [comment]
Actually, the link that I provided is the updated reference:

https://feyncalc.github.io/reference

"FeynCalcBook" is the outdated one that is kept online for legacy reasons.

Am 21.11.2016 um 21:41 schrieb kirtimaan:
