### ISSUE TITLE
Conflict between FeynCalc and PHI

### ISSUE THREAD

**Issue by marti2216** [FeynCalc/feyncalc#171]
*  Your Mathematica version  

  ``13.0.1 for MacOS``

*  Your FeynCalc version   

  ``9.3.1``

*  Did you try to reinstall FeynCalc (stable version) using the automatic installer to make sure that you have the latest bugfixes?   

  ```Yes```

Hello,
I have just starting working with the PHI package and I am trying to compute the Feynman Rules for a 4 pions vertex. I looked to the example given in the PhD thesis of Frederik Orellana but I did not get the same result and I do not understand why. I have basically copied the commands in that example but I get a lot of errors; already when I load FeynCalc I get the message that $Configurations and $Lagrangians appears in multiple context.

I attach my notebook where my code is written to a better comprehension of the problem.

Thanks in advance,
Martina
[test.zip](https://github.com/FeynCalc/feyncalc/files/8538598/test.zip)

**Comment by vsht** [comment]
PHI bugs should be reported in the PHI repository. I do have notifications for all FeynCalc-related repos,
but I don't always have time to react within hours.
