### ISSUE TITLE
Problem when TR encounter gamma5 when using "BMHV" scheme

### ISSUE THREAD

**Issue by QSSRHelper** [FeynCalc/feyncalc#176]
```Matehmatica 12.1```

```FeynCalc 9.3.1```  

  ```No```

  ```(** User Mathematica initialization file **)``` 

*   define something:
  ```
tmp = FVD[x, lor1] FVD[x, lor3] MTD[lor2, lor5] MTD[lor4, lora];
terms = GSD[x].GAD[\[Nu]].GAD[lor5, lorz, lor4] tmp MTD[lora, \[Rho]] MTD[lorb, \[Nu]];

v1a = GA[5].GAD[\[Mu]].GAD[lor1, lorb, lor2, lorz, lor3].GAD[\[Sigma]];
v1b = GAD[\[Sigma]].GAD[lor1, lorb, lor2, lorz, lor3].GA[5].GAD[\[Mu]];
```
* The tr1 =/= tr2 below;  I haven't found another example to reproduce similar problem. there's no problem occurs, e.g. exchange lor2 <-> lor3 in the "tmp" and keep other things.
```
FCSetDiracGammaScheme["BMHV"];
tr1 = TR[v1a.terms - v1b.terms] // Simplify

tr2 = TR[(v1a - v1b).terms] // Simplify
tr2 = Collect[(tr2 // FCI) /. Pair[Momentum[x], Momentum[x]] :> Pair[Momentum[x, D], Momentum[x, D]] - Pair[Momentum[x, D - 4],Momentum[x, D - 4]] // Simplify, Pair[__]]
```
* To be honest, I'm not very familiar with the "BMHV" scheme, but I think the distributive property should be preserved.

**Comment by QSSRHelper** [comment]
* And I find contract after evaluating the trace of gamma matrices has no problem.
```
tmp = FVD[x, lor1] FVD[x, lor3] MTD[lor2, lor5] MTD[lor4, lora] MTD[lora, \[Rho]] MTD[lorb, \[Nu]];
terms = GSD[x].GAD[\[Nu]].GAD[lor5, lorz, lor4];

v1a = GA[5].GAD[\[Mu]].GAD[lor1, lorb, lor2, lorz, lor3].GAD[\[Sigma]];
v1b = GAD[\[Sigma]].GAD[lor1, lorb, lor2, lorz, lor3].GA[5].GAD[\[Mu]];


FCSetDiracGammaScheme["BMHV"];
tr1 = (TR[v1a.terms - v1b.terms] tmp // Contract // Simplify)

tr2 = TR[(v1a - v1b).terms] tmp // Contract // Simplify;
tr2 = Collect[(tr2 // FCI) /. Pair[Momentum[x], Momentum[x]] :>Pair[Momentum[x, D], Momentum[x, D]] - Pair[Momentum[x, D -4], Momentum[x, D - 4]] // Simplify, Pair[__]]
```
* The evaluation of tr2 is time-consuming, it took roughly 2000 seconds on my PC.
* Since only Levi-Civita tensor involve LorentzIndex, and $\hat{\delta}_{\mu\nu}\epsilon^{\nu\rho\sigma\tau}=0$ in BMHV scheme, I think the D-dimensional LorentzIndex can be replaced:

```
tr1 = tr1 /. {LorentzIndex[ll_, _] :> LorentzIndex[ll]} // Simplify

tr2 = tr2 /. {LorentzIndex[ll_, _] :> LorentzIndex[ll]} // Simplify
```
* The tr1 = tr2 , and agree with previous tr1.

**Comment by vsht** [comment]
Many thanks for the bug report. FeynArts would never generate such long nested Dirac matrix
chains, so that this bug obviously never surfaced before.

Could you please check if the fix in the dev version covers your other cases?
I'll back port it to the stable version in the next days.

**Comment by QSSRHelper** [comment]
No problems were found now, thanks!

**Comment by vsht** [comment]
Thanks for the confirmation, the stable version is now fixed as well.
