### ISSUE TITLE
Whats going wrong with DiracTrick ? 

### ISSUE THREAD

**Issue by kirtimaan** [FeynCalc/feyncalc#18]
Dear feyncalc authors,
The following code works with Mathematica v9 and Feyncalc v 9.1.0 :

(1/2 - DiracGamma[5]/2) . (-((mQf + DiracGamma[Momentum[p + q]])/(-mQf^2 + Pair[Momentum[p + q], Momentum[p + q]]))) . 
 (1/2 + DiracGamma[5]/2)// DiracSimplify

 However with Feyncalc v9.2.0 it throws up the following error and Aborts:

"DiracTrick::failmsg: Error! DiracTrick has encountered a fatal problem and must abort the computation. The problem reads: Incorrect combination of dimensions and g^5 scheme! >>"

**Comment by vsht** [comment]
Thanks for the bug report, this should be now fixed. Please reinstall FeynCalc and try again.
