### ISSUE TITLE
Problem of Contract when encounter with D-4 object

### ISSUE THREAD

**Issue by QSSRHelper** [FeynCalc/feyncalc#182]
```13.0.1 for Linux x86 (64-bit) (January 29, 2022) & 12.1.1 for Microsoft Windows (64-bit) (June 9, 2020)```

  ```9.3.1 & 10.0.0```

  ```No```

  ```(** User Mathematica initialization file **)``` 

* Problem of Contract when encounter with D-4 object, e.g.

```
tmp1 = MTD[loor2, lora] MTD[lor1, lor2]  MTE[loor1, lorb] - D MTD[loor1, lora] MTD[lor1, lor2]  MTE[loor2, lorb]
tmp2 = FVD[q, loor1] FVD[q, lor2] MTD[loor2, lor1]  MTD[lora, lorb] + FVD[q, loor1] FVD[q, lor1] MTD[loor2, lor2]  MTD[lora, lorb]
```
* value1=/=value2; the value2 is wrong

```
value1 = Contract[#] & /@ Expand[tmp1 tmp2]
value2 = Contract[tmp1 tmp2]
value1 - value2 // Simplify
```

* I find the definition of pair2 has a problem in [872 line](https://github.com/FeynCalc/feyncalc/blob/17fb239561a08adcd574d30ac55c780d045e6080/FeynCalc/Lorentz/Contract.m#L872)

```
pair2/: pair2[LorentzIndex[al_,___], z_] pair2[LorentzIndex[al_,___], w_]:=pair2[z, w];
```

* e.g. for ```FVD[l1,al] MTE[al,bl] FVD[l2,bl]``` it will become ```SPD[l1,l2]``` but it should be ```SPE[l1,l2]```. Replace ```pair2 -> Pair``` later will hide this problem.

* add these two line can avoid this problem
```
pair2 /: pair2[LorentzIndex[a_, di1___], LorentzIndex[b_, di2___]] :=pair2[LorentzIndex[a, fdi[di1, di2]], LorentzIndex[b, fdi[di1, di2]]] /; di1 =!= di2;
pair2 /: pair2[LorentzIndex[a_, di1___], Momentum[b_, di2___]] :=pair2[LorentzIndex[a, fdi[di1, di2]], Momentum[b, fdi[di1, di2]]] /;di1 =!= di2;
```
* and the [858 line](https://github.com/FeynCalc/feyncalc/blob/17fb239561a08adcd574d30ac55c780d045e6080/FeynCalc/Lorentz/Contract.m#L858) seems redundant.
* 
* But the actual problem may not in here, since ```Contract[FVD[q,lor1] MTE[lor1,lor2] FVD[p,lor2]]``` has no problem. I find it is weird around [130 line](https://github.com/FeynCalc/feyncalc/blob/17fb239561a08adcd574d30ac55c780d045e6080/FeynCalc/Lorentz/Contract.m#L130), if I print the Length of lipa at some step,
```
Print["length:",Length[lipa]];
		If[Length[lipa] < 2,
			time2=AbsoluteTime[];
			FCPrint[1,"Contract: contract3: Applying Contract.", FCDoControl->cnVerbose];
			nec = Contract[lipa, FCI->True, contract3->False, opts];
Print["a---- ",Length[lipa] < 2];			
			FCPrint[1,"Contract: contract3: Contract done. Timing: ", N[AbsoluteTime[] - time2, 4] , FCDoControl->cnVerbose],
Print["b---- ",Length[lipa] < 2];
```
* During the evaluation of value2, it shows  
```
length:2
b---- False
```
* I have no iead what's going on here, seems it can't happen, maybe it's a problem of Mathematica?

**Comment by vsht** [comment]
Thanks for your report, it is indeed a pretty severe bug.

Unfortunately, Contract (along with SUNSimplify and SUNTrace) is one of the few functions that never
got a proper refactoring, which somewhat complicates the matter of narrowing down the precise issue
and making sure that similar things won't happen in the future.

The problem basically comes from the part where Contract tries to handle products of large expressions
in a "smart" way, i.e. without expanding everything term by term.

As an immediate workaround you can set
```
SetOptions[Contract, FeynCalc`Contract`Private`contract3 -> False];
```
For a proper fix I'll need a bit more time to clean up the code of Contract.

**Comment by QSSRHelper** [comment]
Sorry for the stupid words about the problem around 130 line, I haven't notice the comma in the end of FCPrint.
Set contract3->False avoid all my problems, no further problems are found.

**Comment by vsht** [comment]
I rewrote the problematic part of the Contract code, so hopefully such issues should not happen again.
Please check if everything works as intended in the dev version, then I'd back port it to stable.

**Comment by QSSRHelper** [comment]
Thanks for your work, everything works ok now.
