### ISSUE TITLE
Bug about contract

### ISSUE THREAD

**Issue by sesameman** [FeynCalc/feyncalc#194]
*  <summary>Your Mathematica version</summary>    

  ```12.3.1 for Mac OS X ARM (64-bit) (July 24, 2021)```

*  <summary>Your FeynCalc version</summary>    

  ```9.3.1```

*  <summary>Did you try to reinstall FeynCalc (stable version) using the automatic installer to make sure that you have the latest bugfixes?</summary>    

  ```Yes```

*  <summary>Does your Mathematica initialization file contain statements that might influence the behavior of FeynCalc? Sometimes external packages may modify `init.m` in unusual ways, causing troubles for other codes.</summary>    

  ```(** User Mathematica initialization file **)


$Path = Join[{ToFileName[$HomeDirectory, \
"LoopTools/arm64-Darwin/bin"]}, 
  $Path]``` 

*  <summary>Please provide a minimal working example that illustrates the problem and works on a fresh kernel. The example should be provided either by writing the code (as `InputForm`!) directly in the issue text  or by attaching a Mathematica notebook. Please do not post code samples as screenshots, PDF files etc.: Those essentially require us to retype everything by hand, which is annoying and also time consuming. Please explain the difference between the current behavior and the expected behavior.</summary>    

  ```P(FV[p, \[Mu]] SP[k, p] + FV[k, \[Mu]]) . (FV[k, \[Mu]] - 
    FV[p, \[Mu]] SP[k, p]) // TR```


it will show contract problem like this
```"Error! Contract has encountered a fatal problem and must abort the \
computation. The problem reads: \!\(TraditionalForm\`\"Something went \
wrong during prepareProductContractions.\"\)"```

**Comment by vsht** [comment]
Thanks for the bug report. Can you please test the fix in the dev branch? If there are no further issues I'd then back port it to stable.

**Comment by sesameman** [comment]
> Thanks for the bug report. Can you please test the fix in the dev branch? If there are no further issues I'd then back port it to stable.

Bug fixed !Thank you for your dedication !

**Comment by vsht** [comment]
Thanks for the confirmation, the stable version has been updated as well.
