### ISSUE TITLE
Issue with output in Epsilon^four momenta

### ISSUE THREAD

**Issue by physics-hep** [FeynCalc/feyncalc#195]
Dear colleagues,

I get the following factor in one term in the output of an amplitude square calculation:

Overscript[\[Epsilon], _]^(Overscript[p1, _] Overscript[p2, _] Overscript[p3, _] Overscript[p4, _])

where p1, and p2 are four momenta of initial states and p3, and p4 are four momenta of final states.
There is no issue with the four products because other terms are correctly evaluated.
I searched what the Epsilon in the output means in the documentation but could not find any clue.

Could you please help? Thanks.

Best,

**Comment by HBelusca** [comment]
Hello, do you have a minimal example calculation where this error can be reproduced?
It would appear that somehow, either a traditional-form or some pattern passes it through the evaluation.
It seems that the output is meant to be the Levi-Civita symbol \epsilon^{\mu\nu\rho\sigma} contracted with the four momenta p1_\mu, ..., p4_\sigma.

**Comment by vsht** [comment]
Hi,

it's not the first time I'm seeing this question, so I added a line on that to the documentation:
https://feyncalc.github.io/FeynCalcBookDev/LC.html

Hope this helps and I'm closing this issue.

**Comment by physics-hep** [comment]
Thanks Vladyslav,
It was really helpful!
Best,
    On Tuesday, October 11, 2022 at 04:19:31 PM GMT+2, Vladyslav Shtabovenko ***@***.***> wrote:  
 
 


Hi,

it's not the first time I'm seeing this question, so I added a line on that to the documentation:
https://feyncalc.github.io/FeynCalcBookDev/LC.html

Hope this helps and I'm closing this issue.
