### ISSUE TITLE
small problem of FCChargeConjugateTransposed

### ISSUE THREAD

**Issue by QSSRHelper** [FeynCalc/feyncalc#198]
```FeynCalc 10.0.0.```

  ```12.1.1 for Microsoft Windows (64-bit) (June 9, 2020)```

  ```(** User Mathematica initialization file **)``` 

*   FCChargeConjugateTransposed[ _ , Explicit -> True] works not well in some situations, e.g

```
FCChargeConjugateTransposed[GAD[u].(GAD[a, b] - GAD[b, a]), Explicit -> True]
```
the chargeconjugate of ```(GAD[a,b] - GAD[b,a])``` is not shown explicitly.

Practically, such a problem may encounter in some automatic processes like:
```
vertex = DiracSigma[GAD[\[Nu], \[Beta]]];

(* some codes... *)
vertex = ComplexConjugate[vertex];
FCChargeConjugateTransposed[ GAD[\[Mu]]. vertex, Explicit -> True]
```

Add ```ex=DotSimplify[ex]``` before 
	https://github.com/FeynCalc/feyncalc/blob/73434706154958cd1b2ca1f422aac19776767483/FeynCalc/Dirac/FCChargeConjugateTransposed.m#L103		

can avoid this problem, but I'm not sure whether such modification will cause other problems.

**Comment by vsht** [comment]
I agree that this needs to be improved, but I'd like to check first whether one can find a somewhat less invasive solution...

**Comment by vsht** [comment]
Sorry that it took so long. I pushed a fix to the dev version that should take care of this.
Please let me know if this fixes all the relevant cases. Then I would also add that
to the stable version.

**Comment by cencen06** [comment]
> 
>   ```FeynCalc 10.0.0.```
> 
>   ```12.1.1 for Microsoft Windows (64-bit) (June 9, 2020)```
> 
>   ```(** User Mathematica initialization file **)``` 
> 
> *   FCChargeConjugateTransposed[ _ , Explicit -> True] works not well in some situations, e.g
> 
> ```
> FCChargeConjugateTransposed[GAD[u].(GAD[a, b] - GAD[b, a]), Explicit -> True]
> ```
> the chargeconjugate of ```(GAD[a,b] - GAD[b,a])``` is not shown explicitly.
> 
> Practically, such a problem may encounter in some automatic processes like:
> ```
> vertex = DiracSigma[GAD[\[Nu], \[Beta]]];
> 
> (* some codes... *)
> vertex = ComplexConjugate[vertex];
> FCChargeConjugateTransposed[ GAD[\[Mu]]. vertex, Explicit -> True]
> ```
> 
> Add ```ex=DotSimplify[ex]``` before 
> 	https://github.com/FeynCalc/feyncalc/blob/73434706154958cd1b2ca1f422aac19776767483/FeynCalc/Dirac/FCChargeConjugateTransposed.m#L103		
> 
> can avoid this problem, but I'm not sure whether such modification will cause other problems.

**Comment by QSSRHelper** [comment]
Sorry that I nearly forgot this issue. I tested and everything works ok now. Thanks for your work.
