### ISSUE TITLE
Message Failure when installing Stable on Mathematica 10

### ISSUE THREAD

**Issue by crockpotveggies** [FeynCalc/feyncalc#2]
Not sure if this is normal or not, but got a weird error when running the internet install for the latest Stable release on Mathematica 10:

![screen shot 2015-03-27 at 3 40 42 pm](https://cloud.githubusercontent.com/assets/1445295/6878285/c9dd26c0-d498-11e4-9f67-89f80ca939c4.png)

**Comment by vsht** [comment]
Please follow the steps in
https://github.com/FeynCalc/feyncalc/wiki/FeynArts#patching_fa 

and make sure that $FeynArtsDirectory points to the directory where you put FeynArts.

**Comment by crockpotveggies** [comment]
Just to be clear here, this was using the internet install method, or rather:

```
Import["http://www.feyncalc.org/install.m"]
```

I was, however, able to remedy the issue by removing all FeynCalc files from Mathematica/Applications and used one of the nightlies. Seems a little weird, but maybe its something finicky in Mathematica 10?

**Comment by vsht** [comment]
I know. The version 8.2 actually came out almost three  years ago
<http://www.feyncalc.org/download/>.
and the active development was restarted only last year.

The current development version is much more thoroughly tested 
and has got a lot of bug fixes and improvements. However, it is 
still not quite where we want it to be for a proper release.

**Comment by crockpotveggies** [comment]
Ah got it, I'll close this issue then. Anything I can do to help? Do you have a mailing list?

**Comment by vsht** [comment]
The mailing list is here:
http://www.feyncalc.org/forum/

Testers are always wanted. If you happen to be a particle physicist,  you can check your results with FeynCalc and report bugs or suggest improvements.
