### ISSUE TITLE
Minor problem with SUNSimplify

### ISSUE THREAD

**Issue by NefedovM** [FeynCalc/feyncalc#208]
*  <summary>Your Mathematica version</summary>    

$Version ="12.0.0 for Linux x86 (64-bit) (April 7, 2019)"

*  <summary>Your FeynCalc version</summary>    

  $FeynCalcVersion = "10.0.0"

*  <summary>Did you try to reinstall FeynCalc (stable version) using the automatic installer to make sure that you have the latest bugfixes?</summary>    

development version

*  <summary>Does your Mathematica initialization file contain statements that might influence the behavior of FeynCalc? Sometimes external packages may modify `init.m` in unusual ways, causing troubles for other codes.</summary>    

  ```Check the output of Import[FileNameJoin[{$UserBaseDirectory, "Kernel", "init.m"}], "String"]``` 

*  <summary>Please provide a minimal working example that illustrates the problem and works on a fresh kernel. The example should be provided either by writing the code (as `InputForm`!) directly in the issue text  or by attaching a Mathematica notebook. Please do not post code samples as screenshots, PDF files etc.: Those essentially require us to retype everything by hand, which is annoying and also time consuming. Please explain the difference between the current behavior and the expected behavior.</summary>    

  Hi. I have found that evaluating
    SUNTrace[SUNT[a].SUNT[b].SUNT[c] - SUNT[c].SUNT[b].SUNT[a]]
    SUNSimplify[%] // InputForm

produces:
    (I/2)*SUNF[SUNIndex[FCGV["sun6891"]], SUNIndex[FCGV["sun6892"]], SUNIndex[FCGV["sun6893"]]]

while 
  SUNTrace[SUNT[a].SUNT[b].SUNT[c]] - SUNTrace[SUNT[c].SUNT[b].SUNT[a]]
  SUNSimplify[%] // InputForm

produces the expected result:
  (I/2)*SUNF[SUNIndex[a], SUNIndex[b], SUNIndex[c]]

 It seems that in the first example, the SUNSimplify have counted variables a,b,c inside SUNTrace twice, decided that these are dummy indices and have renamed them.  Of course it is possible to avoid this problem by not putting more than one term into SUNTrace. But I think that linearity of the trace is a reasonable property to expect. This behavior have lead to error messages with some of my older code, which did not pop-up with FC v.9x but started to appear in v. 10.

**Comment by vsht** [comment]
Hi Maxim,

thanks a lot for this bug report. The output here is clearly incorrect, but it is also rather easy to fix, given
that now the source code of `SUNSimplify` / `SUNTrace` is very clean and readable.

Please try reinstalling the dev version, the bugfix should be already there.

Cheers,
Vladyslav

**Comment by NefedovM** [comment]
Hi Vladyslav,
yes, after reinstalling the dev. version the 

  `SUNTrace[SUNT[a].SUNT[b].SUNT[c] - SUNT[c].SUNT[b].SUNT[a]]
SUNSimplify[%] // InputForm`

produces

`(I/2)*SUNF[SUNIndex[a], SUNIndex[b], SUNIndex[c]]`

thank you.

All the best,
Maxim

**Comment by vsht** [comment]
Thanks for the confirmation!
