### ISSUE TITLE
Sign difference between massive and massless spinors?

### ISSUE THREAD

**Issue by kirtimaan** [FeynCalc/feyncalc#21]
In[51]:= SpinorVBar[k2,m]//FCI //StandardForm
Out[51]//StandardForm= Spinor[-Momentum[k2],m,1]

**Whereas**

In[52]:= SpinorVBar[k2]//FCI //StandardForm
Out[52]//StandardForm= Spinor[Momentum[k2],0,1]

**Why is there a difference in sign of the momenta in these two cases ?**

**Similarly**

In[67]:= Spinor[-k2].GA[\[Mu]].Spinor[k1] //FCI //StandardForm
Out[67] Spinor[-Momentum[k2],0,1].DiracGamma[LorentzIndex[\[Mu]]].Spinor[Momentum[k1],0,1]

 **Whereas** 

In[66]:= SpinorVBar[k2]. GA[\[Mu]].SpinorU[k1] //FCI //StandardForm
Out[66]=Spinor[Momentum[k2],0,1].DiracGamma[LorentzIndex[\[Mu]]].Spinor[Momentum[k1],0,1]

**Comment by vsht** [comment]
This has nothing to do with massive or massless.
`Spinor[U/V](Bar)` are just placeholders for Spinor 
and make little sense when not inside a closed spinor chain. 
Inside Spinor the sign in front of Momentum is used to distinguish
between U and V spinors, c.f.

https://github.com/FeynCalc/feyncalc/wiki/FAQ#spinors

or

http://www.feynarts.de/FA3Guide.pdf p. 73

Compare the output of 

```
SpinorUBar[p1].GS[q].SpinorU[p2] // FCI // StandardForm
SpinorUBar[p1].GS[q].SpinorV[p2] // FCI // StandardForm
SpinorVBar[p1].GS[q].SpinorU[p2] // FCI // StandardForm
SpinorVBar[p1].GS[q].SpinorV[p2] // FCI // StandardForm
```
