### ISSUE TITLE
Some images on the online reference are not available

### ISSUE THREAD

**Issue by cyliu-phy** [FeynCalc/feyncalc#219]
I'm a new learner of FeynCalc, when I refer to the online documentation, some images can not be loaded. At first I thought it was network issue, but after changing sever network proxy it still didn't work.
For example, the following page 

https://feyncalc.github.io/FeynCalcBook/ref/FeynRule.html

<img width="394" alt="image" src="https://user-images.githubusercontent.com/71125015/231782967-2542d49a-9f9a-49df-83bc-48cd32a2bf55.png">

**Comment by vsht** [comment]
I can confirm that this issues occurs with Chrome-based browsers, while Firefox works fine.

Howevever, that documentation is already sort of outdated and will be retired once FeynCalc 10 is released. 

So I'd rather recommend to switch to the dev version of the package and use

https://feyncalc.github.io/referenceDev

or download the whole thing as a PDF file from

https://github.com/FeynCalc/feyncalc-manual/releases/tag/dev-manual

**Comment by cyliu-phy** [comment]
> 

Thanks for your replay!
