### ISSUE TITLE
Problem on E0 scalar function

### ISSUE THREAD

**Issue by PabloSanchezPuertas** [FeynCalc/feyncalc#22]
Hello Again, 
I just use GitHub in order to upload a minimal working example to highlight the issues commented on the mailing list "E0 scalar function". 
As said, for the E0 scalar function, I get an overall minus sign with respect to the one I find implementing the Denner-Dittmaier algorithm in FeynCalc and also with respect to the LoopTools E0[ee0,pi...,,mi,...] implementation. 
I show that numerically for a particular point of the phase-space in my problem.
Because GitHub does not allow *.nb extensions I just compressed that into an allowed zip file, I hope that works. Alternativley, find the MWE.nb file at 
https://github.com/PabloSanchezPuertas/Mathematica
[MWE.zip](https://github.com/FeynCalc/feyncalc/files/726358/MWE.zip)

**Comment by vsht** [comment]
Thanks. Should be now fixed.
