### ISSUE TITLE
Cyclicity of the color trace

### ISSUE THREAD

**Issue by NefedovM** [FeynCalc/feyncalc#224]
*  <summary>Your Mathematica version</summary>    
13.0.1 for Linux x86 (64-bit) (January 29, 2022)

*  <summary>Your FeynCalc version</summary>    
"10.0.0" (development)

*  <summary>Did you try to reinstall FeynCalc (stable version) using the automatic installer to make sure that you have the latest bugfixes?</summary>    

  No, should I? 

Hi, everyone
  evaluating

 ` SUNSimplify[SUNTrace[SUNT[a, a, b, b]]] // InputForm `

I get

 ` SUNTrace[SUNT[SUNIndex[FCGV["sun16131"]]] . SUNT[SUNIndex[FCGV["sun16131"]]] . 
  SUNT[SUNIndex[FCGV["sun16132"]]] . SUNT[SUNIndex[FCGV["sun16132"]]]] `

while evaluating an equivalent expression

 ` SUNSimplify[SUNTrace[SUNT[a, b, b, a]]] // InputForm`

I get

 ` CA*CF^2`

as it should be.

So the cyclic property of the color trace doesn't seem to always work. Is it a known issue?

M.N.

**Comment by vsht** [comment]
Hi Maxim,

many thanks for the bug report. I'll upload the fix tomorrow, but for the moment you can just use the option SUNTraceEvaluate->True, which is set to Automatic by default.

Am 20. Juni 2023 16:12:25 UTC schrieb NefedovM ***@***.***>:

**Comment by vsht** [comment]
The issue should be now fixed, feel free to reopen if there are still remaining problems.
