### ISSUE TITLE
Probelm in Trace in Feyncalc 9.2.0

### ISSUE THREAD

**Issue by sbilmis** [FeynCalc/feyncalc#23]
Hi, 
In Feyncalc 9.0.0 when I tried to evaluate; (Mathematica 10.2.0.0 MacOS)
Tr[DiracSigma[GA[a],GA[b]].GA[a].GA[b] 
I get -48i.

However when I tried the same command with FeynCalc 9.2.0 I get; (Mathematica 11.0.1.0 MacOS)
tr(\sigma^{ab} . \gamma^a . \gamma^b)
It does not evaluate but simply writes the output.

On the other hand, when I evaluate
Tr[GA[a].GA[b]] 
 I get the correct result. 

It seems the problem is due to DiracSigma. Is there a change in the new version or am I missing some trivial things?

How can I solve it?

Thanks in advance.

Selcuk

**Comment by vsht** [comment]
Hi Selcuk,

this is an unfortunate omission that occurred while rewriting the internal logic of DiracTrace. Should be now fixed. Please reinstall FeynCalc 9.2 via the automatic installer.

Cheers,
Vladyslav

**Comment by sbilmis** [comment]
That solved my problem. 

Thank you.
