### ISSUE TITLE
Some thing wrong between Integrate and TR ( when they working on GA[a] )

### ISSUE THREAD

**Issue by sesameman** [FeynCalc/feyncalc#233]
*  <summary>Your Mathematica version</summary>    

  ```13.2.0 for Mac OS X x86 (64-bit) (November 18, 2022)```

*  <summary>Your FeynCalc version</summary>    

  ```9.3.1```

*  <summary>Did you try to reinstall FeynCalc (stable version) using the automatic installer to make sure that you have the latest bugfixes?</summary>    

  ```Yes```

*  <summary>Does your Mathematica initialization file contain statements that might influence the behavior of FeynCalc? Sometimes external packages may modify `init.m` in unusual ways, causing troubles for other codes.</summary>    

  ```(** User Mathematica initialization file **)`` 

*  <summary>Please provide a minimal working example that illustrates the problem and works on a fresh kernel. The example should be provided either by writing the code (as `InputForm`!) directly in the issue text  or by attaching a Mathematica notebook. Please do not post code samples as screenshots, PDF files etc.: Those essentially require us to retype everything by hand, which is annoying and also time consuming. Please explain the difference between the current behavior and the expected behavior.</summary>    

```
(*I want to calculate `GS[p]`dot`GS[q]` in a Inactivate Integral like this :*)
Inactivate[Integrate[GS[p] . GS[q], p], Integrate] // TR
(*Just like you see, it dones't work.*)
(*May be its something wrong with Integral*)
Inactivate[Integrate[GS[k] . GS[q], p], Integrate] // TR
Inactivate[Integrate[GA[a] . GA[b], p], Integrate] // TR
(*Don't work too*)
```
[gethelp.nb.zip](https://github.com/FeynCalc/feyncalc/files/12702757/gethelp.nb.zip)

**Comment by vsht** [comment]
First of all, `Integrate` is a Mathematica command for 1-D integration, while here you have an expression depending on
a 4-vector. So I don't even know what `Integrate[...,p]` is supposed to mean.

Second, in most cases you need to use FeynCalc functions to manipulate FeynCalc symbols in a meaningful way, not just random Mathematica routines.
