### ISSUE TITLE
Error in the simplifications of Dirac matrices involving Light Cone perpendicular vectors (in D dimension)

### ISSUE THREAD

**Issue by maxferrre** [FeynCalc/feyncalc#245]
. Your Mathematica version  

  13.3.1 for Mac OS X ARM (64-bit) (July 24, 2023)

. Your FeynCalc version 

  10.0.0

.Did you try to reinstall FeynCalc (stable version) using the automatic installer to make sure that you have the latest bugfixes?

No, but I did check with the latest master branch. 

.Does your Mathematica initialization file contain statements that might influence the behavior of FeynCalc? Sometimes external packages may modify `init.m` in unusual ways, causing troubles for other codes. 

  No.

.Please provide a minimal working example that illustrates the problem and works on a fresh kernel. The example should be provided either by writing the code (as `InputForm`!) directly in the issue text  or by attaching a Mathematica notebook. Please do not post code samples as screenshots, PDF files etc.: Those essentially require us to retype everything by hand, which is annoying and also time consuming. Please explain the difference between the current behavior and the expected behavior.   

<< FeynCalc`
GSLRD[p] . GALRD[mu] . GSLRD[p]
DiracTrick[%]

OutPut (in InputForm) : 2*DiracGamma[LightConePerpendicularComponent[Momentum[p, D], Momentum[FCGV["n"], D], 
    Momentum[FCGV["nb"], D]], D]*Pair[LightConePerpendicularComponent[
    LorentzIndex[mu, D], Momentum[FCGV["n"], D], Momentum[FCGV["nb"], D]], 
   LightConePerpendicularComponent[Momentum[p, D], Momentum[FCGV["n"], D], 
    Momentum[FCGV["nb"], D]]] - 
 DiracGamma[LightConePerpendicularComponent[LorentzIndex[mu, D], 
    Momentum[FCGV["n"], D], Momentum[FCGV["nb"], D]], D]*
  Pair[Momentum[p, D], Momentum[p, D]]

the second term should involve "Pair[LightConePerpendicularComponent[Momentum[p, D], Momentum[FCGV["n"], D], 
    Momentum[FCGV["nb"], D],LightConePerpendicularComponent[Momentum[p, D], Momentum[FCGV["n"], D], 
    Momentum[FCGV["nb"], D]]" (the scalar product between the perpendicular components of p), not the full scalar product "Pair[Momentum[p, D], Momentum[p, D]]".

NB : This mistake is not there if I work with dimension 4 objects.

Thank you in advance for your time :)

**Comment by vsht** [comment]
Hi,

many thanks for the bug report. Could you please check if the fix in the dev version covers all your usage cases?

After that I would push that into stable.

**Comment by maxferrre** [comment]
Hi,

Thank you for the bug fixing, I can confirm that with this fix my different cases are now giving me the expected results.
