### ISSUE TITLE
Apparent bug in SUNSimplify and/or ComplexConjugate

### ISSUE THREAD

**Issue by hac43** [FeynCalc/feyncalc#259]
*  <summary>Your Mathematica version</summary>    
```
In[1]:= $Version

Out[1]= 13.2.1 for Linux x86 (64-bit) (January 27, 2023)
```

*  <summary>Your FeynCalc version</summary>    

```
In[3]:= $FeynCalcVersion

Out[3]= 10.0.0
```

*  <summary>Did you try to reinstall FeynCalc (stable version) using the automatic installer to make sure that you have the latest bugfixes?</summary>    

  ```Yes```

*  <summary>Does your Mathematica initialization file contain statements that might influence the behavior of FeynCalc? Sometimes external packages may modify `init.m` in unusual ways, causing troubles for other codes.</summary>    

  ```Check the output of Import[FileNameJoin[{$UserBaseDirectory, "Kernel", "init.m"}], "String"]``` 

```
(** User Mathematica initialization file **)

Get[ToFileName["/home/hac43/.Mathematica/Autoload","init.m"]]

$Path = Join[{ToFileName[$HomeDirectory, 
    "usr/src/feynarts/LoopTools/x86_64-Linux/bin"]}, $Path]

$Path = Join[{ToFileName[$HomeDirectory, "usr/src/feynarts/FeynArts"], 
   ToFileName[$HomeDirectory, "usr/src/feynarts/FormCalc"], 
   ToFileName[$HomeDirectory, 
    "usr/src/feynarts/LoopTools/x86_64-Linux/bin"]}, $Path]
```

*  <summary>Please provide a minimal working example that illustrates the problem and works on a fresh kernel. The example should be provided either by writing the code (as `InputForm`!) directly in the issue text  or by attaching a Mathematica notebook. Please do not post code samples as screenshots, PDF files etc.: Those essentially require us to retype everything by hand, which is annoying and also time consuming. Please explain the difference between the current behavior and the expected behavior.</summary>    

**Input:**
```
<< FeynCalc`;
g1 = ((SUNN*SUNF[SUNIndex[a1], SUNIndex[Glu1], SUNIndex[Glu2]]*
      SUNTF[{SUNIndex[a1]}, SUNFIndex[Col3], SUNFIndex[Col4]]) + (I)*
     SUNN*SUNTF[{SUNIndex[Glu1]}, SUNFIndex[i5], SUNFIndex[Col4]]*
     SUNTF[{SUNIndex[Glu2]}, SUNFIndex[Col3], SUNFIndex[i5]] - (I)*
     SUNN*SUNTF[{SUNIndex[Glu1]}, SUNFIndex[Col3], SUNFIndex[i5]]*
     SUNTF[{SUNIndex[Glu2]}, SUNFIndex[i5], SUNFIndex[Col4]]);
g2 = ComplexConjugate[g1];
g3 = -(SUNF[SUNIndex[a1], SUNIndex[a2], SUNIndex[Glu1]]*
     SUNF[SUNIndex[a2], SUNIndex[a3], SUNIndex[Glu2]]*
     SUNTF[{SUNIndex[a1], SUNIndex[a3]}, SUNFIndex[Col3], 
      SUNFIndex[Col4]]);
g4 = ComplexConjugate[ComplexConjugate[g3]];
Simplify[SUNSimplify[g2*g4, SUNNToCACF -> False]]
Simplify[SUNSimplify[g2*g3, SUNNToCACF -> False]]
```
**Output:**
```
Out[6]= 1/4 I N^3 (N^2-1)

Out[7]= 0
```
**Expected output:**
I would have expected the two outputs to be identical to each other, since g3 and g4 are (or should be) identical to each other.

**Comment by hac43** [comment]
Many thanks for this. It seems to have fixed the problem, both for the minimal example and the rest of my calculation. Thanks a lot.

**Comment by vsht** [comment]
Thanks for the confirmation.
