### ISSUE TITLE
QEDComptonScatteringTree returning the wrong value 

### ISSUE THREAD

**Issue by patha325** [FeynCalc/feyncalc#26]
The in feyncalc, included example of a QEDComptonScatteringTree returns the wrong value.
Mathematica version 11.0.0.0
Mac OS X x86 (32-bit, 64-bit kernel)
Using an out of the box installation of mathematica and feyncalc using
Import["https://raw.githubusercontent.com/FeynCalc/feyncalc/master/install.m"]; InstallFeynCalc[]

I would love to know what is wrong since this makes no sense to me at all.
It might be the setmandelstram?
[QEDComptonScatteringTree.pdf](https://github.com/FeynCalc/feyncalc/files/911472/QEDComptonScatteringTree.pdf)

**Comment by patha325** [comment]
Full reinstall of mathematica sorted things out. Must have been something wrong with the installer?

**Comment by vsht** [comment]
Your version of QEDComptonScatteringTree.m looks a bit weird. In particular, the line 
```
SetMandelstam[s, t, u, p1, k1, -p2, -k2, SMP["m_e"], 0];
```
is not correct. Compare this to [how it should look like](https://github.com/FeynCalc/feyncalc/blob/hotfix-stable/FeynCalc/Examples/QED/QEDComptonScatteringTree.m#L57).
Did you modify the example file yourself before running it?

I use Mathematica 11.0 myself (albeit on Linux) and I usually run all available tests and examples before pushing anything into the [hotfix-stable](https://github.com/FeynCalc/feyncalc/tree/hotfix-stable) branch, which is what automatic installer uses.

So far there were no complaints about automatic installer fetching wrong files. At most I could imagine that if you first use the installer and then try to clone git repository in the same directory, there might be unwanted interference. However, for people who want to use git themselves, there is a separate [section](https://github.com/FeynCalc/feyncalc/wiki/Installation#dev_manual_installation_with_git_on_linux) in the wiki, that does not require the installer.

**Comment by patha325** [comment]
Dear Sir,
I did not edit anything before running it but as I added when closing the
thread a full reinstall solved this issue.

Since I used the automatic installer, that is where I would assume the
fault came from. But I am grasping at straws.

MVH/Kind regards
Patrik Hallsjö

2017-04-11 17:36 GMT+02:00 Vladyslav Shtabovenko <notifications@github.com>:

**Comment by vsht** [comment]
In this case I really don't know. The [installer](https://github.com/FeynCalc/feyncalc/blob/hotfix-stable/install.m) essentially downloads 
<https://github.com/FeynCalc/feyncalc/archive/hotfix-stable.zip>
from GitHub and extracts it to the right directory using 
Mathematica's `ExtractArchive`. I cannot easily think of anything going
wrong there. In any case, if you manage to make the issue reproducable, 
let me know.
