### ISSUE TITLE
Calculating Singular Integrals

### ISSUE THREAD

**Issue by martinjm97** [FeynCalc/feyncalc#266]
Hello,

I have had some trouble getting the library to fully evaluate some singular integrals. For example:

```
>>> N[Integral2[x/(1/2 - x), {x, -1, 1}]]
Integral2(x/(0.5 -1. x),{x,-1.,1.})

>>> N[Integral2[x/(1/2 - x)^2, {x, -1, 1}]]
Integral2(x/(0.5 -1. x)^2,{x,-1.,1.})
```
I'd expect a number as outputs for these examples rather than an expression. 

I'm sorry if this is a simple problem. I am not an experienced user of Mathematica.

Answers to the provided questions:
* Mathematica version:  ```14.0.0 for Mac OS X x86 (64-bit) (December 13, 2023)```
* FeynCalc version: 10.0.0
* I used the automatic installer.
* The output of Import[FileNameJoin[{$UserBaseDirectory, "Kernel", "init.m"}], "String"] is "(** User Mathematica initialization file **)"

Thank you!

**Comment by martinjm97** [comment]
Thank you for the response! Are there other ways to calculate these sorts of integrals in FeynCalc? 

--Jesse

**Comment by vsht** [comment]
If you know how to handle plus distributions by hand it shouldn't be difficult to cook something with Mathematica alone.
I don't think that FeynCalc is even needed for that.

**Comment by martinjm97** [comment]
Got it. Thank you! I'll close off the issue.
