### ISSUE TITLE
FCGetFreeIndices obtain a wrong result when the amplititude contains DiracTrace

### ISSUE THREAD

**Issue by Zhongyuan-Liu** [FeynCalc/feyncalc#269]
*  <summary>Your Mathematica version</summary>    

  ```13.3.1 for Linux x86 (64-bit) (July 24, 2023)```

*  <summary>Your FeynCalc version</summary>    

  ```10.0.0```

*  <summary>Did you try to reinstall FeynCalc (stable version) using the automatic installer to make sure that you have the latest bugfixes?</summary>    

  ```No```
But I have tried in another computer, whose FeynCalc is a stable version.
*  <summary>Does your Mathematica initialization file contain statements that might influence the behavior of FeynCalc? Sometimes external packages may modify `init.m` in unusual ways, causing troubles for other codes.</summary>    

It seems to have no problem. The information is include in the following attachment.

The examples are included in the following attachment. I cannot upload a *.nb file, so I change the file name into .md.
[Untitled-2.md](https://github.com/FeynCalc/feyncalc/files/15337114/Untitled-2.md)

**Comment by vsht** [comment]
Thanks for the bug report. I think this should be now fixed. Could you please test the dev version to make sure  it covers all relevant cases?

**Comment by Zhongyuan-Liu** [comment]
I have downloaded  the master branch and tested.
The bug doesn't seem to have been completely resolved. The following code 
`DiracTrace[Dot[GSD[p3 + p4] + m, GAD[mu], GAD[nu]]]`
`FCGetFreeIndices[FullForm[FCI[%[[1]]]], {LorentzIndex}]`
still gives a wrong result, although other examples are correct now. If I get rid of the `FullForm[]` or the mass `m`, it gives correct result. 

Moreover, I wonder why the output become plain text
![image](https://github.com/FeynCalc/feyncalc/assets/147290639/d7abe120-2508-4abe-8e50-0f62f883048a)
rather than previous easy reading 
![image](https://github.com/FeynCalc/feyncalc/assets/147290639/1004cb2f-cae6-4122-9b89-58cc5719ed15).
Does it a bug? Or just I should use some function to set the format of my output result?

**Comment by vsht** [comment]
> If I get rid of the FullForm[] or the mass m, it gives correct result.

You answered your question yourself. Never wrap FullForm over expressions to be further processed in Mathematica. It's only for displaying something. The same goes for TraditionalForm, StandardForm, MatrixForm etc.

This works as expected
```
DiracTrace[Dot[GSD[p3 + p4] + m, GAD[mu], GAD[nu]]]
FCGetFreeIndices[FCI[%], {LorentzIndex}]
```

**Comment by Zhongyuan-Liu** [comment]
OK! Thank you for your help!
