### ISSUE TITLE
PaVe function pattern goes into infinite loop 

### ISSUE THREAD

**Issue by ChiMaoShuPhy** [FeynCalc/feyncalc#27]
I was trying to make a PaVe function pattern

`PaVe[0,{a_,b_,c_},{d_,e_,f_}]` 

If I evaluate it twice, if will go into infinite loop

`$IterationLimit::itlim: Iteration limit of 4096 exceeded.

$RecursionLimit::reclim2: Recursion depth of 4096 exceeded during evaluation of Refresh[TraditionalFormDump`$UseNewTraditionalForm,None].

$RecursionLimit::reclim2: Recursion depth of 4096 exceeded during evaluation of Refresh[TraditionalFormDump`$UseNewTraditionalForm,None].

$RecursionLimit::reclim2: Recursion depth of 4096 exceeded during evaluation of BoxForm`MakeTraditionalBoxes(Pattern).

General::stop: Further output of $RecursionLimit::reclim2 will be suppressed during this calculation.`

**Comment by vsht** [comment]
Thanks for the bug report, should be now fixed via 26f70eaac8042ca94. Please reinstall and report if
it works for you.

Cheers,
Vladyslav

**Comment by ChiMaoShuPhy** [comment]
Thanks a lot for the fix and now it works well.

Cheers,
Xiaonu
