### ISSUE TITLE
Problem installing FeynArts with automatic installer

### ISSUE THREAD

**Issue by irina-ru** [FeynCalc/feyncalc#277]
*  <summary>Your Mathematica version</summary>    

  ```14.0.0 for Mac OS X x86 (64-bit) (December 13, 2023)```

*  <summary>Your FeynCalc version</summary>    

  ```10.0.0```

*  <summary>Did you try to reinstall FeynCalc (stable version) using the automatic installer to make sure that you have the latest bugfixes?</summary>    

  ```Yes```

I used the auto installer to install FeynCalc and FeynArts together with 
```mathematica
Import["https://raw.githubusercontent.com/FeynCalc/feyncalc/master/install.m"];
InstallFeynCalc[]
```
However, while the installation for FeynArts did not work, as the FeynArts zip-file might be corrupted. The output of the installation:
```
Downloading FeynCalc from https://github.com/FeynCalc/feyncalc/archive/hotfix-stable.zip ...done! 
FeynCalc zip file was saved to /private/var/folders/_z/zvxt4qsn281bxkvs4prh_xcr0000gn/T/m00000516461.
Extracting FeynCalc zip file to /private/var/folders/_z/zvxt4qsn281bxkvs4prh_xcr0000gn/T/m00000516461.dir ...done! 
Checking the directory structure...done! 
Copying FeynCalc to /Users/myname/Library/Mathematica/Applications/FeynCalc ...done! 
Setting up the format type of new output cells ... done! 
Creating the configuration file ... done! 
Downloading FeynArts from https://github.com/FeynCalc/feynarts-mirror/archive/master.zip ...done! 
FeynArts zip file was saved to /private/var/folders/_z/zvxt4qsn281bxkvs4prh_xcr0000gn/T/m00000616461.
Extracting FeynArts zip file to /Users/myname/Library/Mathematica/Applications/FeynCalc/FeynArts ...
Failed to extract the FeynArts zip. The file might be corrupted.
Installation aborted!
```
together with an ```ExtractArchive::noopen``` error message. Reinstalling doesn't seem to fix the issue.

**Comment by vsht** [comment]
Thanks for the bug report. It affects only Mathematica 14 and should be now fixed.

**Comment by irina-ru** [comment]
Thank you, installation seems to have worked just fine!
