### ISSUE TITLE
Output format type

### ISSUE THREAD

**Issue by Turgon-Aran-Gondolin** [FeynCalc/feyncalc#28]
Is it possible to set the output format type as TraditionalForm every time the package is loaded? Such as insert SetOptions[EvaluationNotebook[],CommonDefaultFormatTypes->{"Output"->TraditionalForm}] in it?

**Comment by vsht** [comment]
Yes, you can put any Mathematica command into `FCConfig.m`. That file is always evaluated before
FeynCalc is loaded.

**Comment by Turgon-Aran-Gondolin** [comment]
OK thanks
