### ISSUE TITLE
Write2 not fully working

### ISSUE THREAD

**Issue by rolfmertig** [FeynCalc/feyncalc#3]
"Isolated" expressions are not converted to nice Fortran files as described here 
http://www.feyncalc.org/FeynCalcBook/Write2/

```
Mathematica 10.1.0 for Linux x86 (64-bit)
Copyright 1988-2015 Wolfram Research, Inc.

In[1]:= !!t.m

Needs["FeynCalc`"];
(* assuming you use Fortran 90 or newer*)
$FortranContinuationCharacter = "";
t2 = x + Collect2[((a-c)^2 + (a-b)^2)^2,a,IsolateNames -> L];
Write2["t2.f", r = t2, FormatType -> FortranForm]
FilePrint @ "t2.f"
Print["t2 = ", t2 // InputForm];
Print["DownValues[L] = ", DownValues[L] // InputForm];

In[2]:= <<t.m
Loading FeynCalc from /home/rolfm/.Mathematica/Applications/FeynCalc/
$PrePrint is set to FeynCalcForm. Use FI and FC to change the display format.
FeynCalc 9.0.0. For help, type ?FeynCalc, use the help browser or visit www.feyncalc.org.
        L(24D1)= L(24D1)
        L(25D1)= L(25D1)
        L(26D1)= L(26D1)
        r = 4D0*a**4 + x - 8D0*a**3*L(24D1) + 8D0*a**2*L(25D1) -
       4D0*a*L(24D1)*L(26D1) + L(26D1)**2

t2 = 4*a^4 + x - 8*a^3*HoldForm[L[24]] + 8*a^2*HoldForm[L[25]] - 4*a*HoldForm[L[24]]*HoldForm[L[26]] + HoldForm[L[26]]^2
DownValues[L] = {HoldPattern[L[24]] :> b + c, HoldPattern[L[25]] :> b^2 + b*c + c^2, HoldPattern[L[26]] :> b^2 + c^2}
```

**Comment by vsht** [comment]
True, this should be fixed. I'll look into this.

**Comment by rolfmertig** [comment]
Thanx.
I wanted to use it for an answer on SE,
therefore I noticed it.
Sorry for not fixing it, but I just don't have much time.
Rolf
Am 17.05.2015 02:23 schrieb "Vladyslav Shtabovenko" <
notifications@github.com>:

**Comment by vsht** [comment]
I think found the issue and fixed it:
d4decd5b5acc2f10d813580712f3552f2627464a

Essentially, it comes from

    Isolate[a + b]
    N[%]
    FRH[%]

Since `KK[1]` is not the same as `KK[1.]`. Is this ok now?

    Needs["FeynCalc`"];
    $FortranContinuationCharacter = "";
    t2 = x + Collect2[((a - c)^2 + (a - b)^2)^2, a, IsolateNames -> L];
    Write2["t2.f", r = t2, FormatType -> FortranForm];
    FilePrint@"t2.f"

        L(24)= b + c
        L(25)= b**2 + b*c + c**2
        L(26)= b**2 + c**2
        r = 4D0*a**4 + x - 8D0*a**3*L(24) + 8D0*a**2*L(25) - 
       4D0*a*L(24)*L(26) + L(26)**2

**Comment by vsht** [comment]
Can we close the issue now, or is there still something not working in Write2?

**Comment by rolfmertig** [comment]
Great! You can close it. The question is if we should change $FortranContinuatioCharacter = "" by default, but this is of course unrelated to this issue.
