### ISSUE TITLE
A minor issue with FCFAConvert

### ISSUE THREAD

**Issue by DexKim** [FeynCalc/feyncalc#31]
*  <summary>Your Mathematica version</summary>    

  ```11.1.1 for Microsoft Windows (64-bit) (April 18, 2017)```

*  <summary>Your FeynCalc version</summary>    

  ```9.2.0```

*  <summary>Did you try to reinstall FeynCalc (stable version) using the automatic installer to make sure that you have the latest bugfixes?</summary>    

  ```Yes```

*  <summary>Please provide a minimal working example that illustrates the problem. Please explain the difference between the current behavior and the expected behavior.</summary>    

The function FCFAConvert seems to have problems with substituting indices in FASUNF(a,b,c,d). For example, when the following code is evaluated

  ```
t4 = CreateTopologies[0, 4];
gggg = InsertFields[t4, {V[5], V[5], V[5], V[5]} -> {}, 
   InsertionLevel -> {Classes}, Model -> "SMQCD"];
ggggAmp = 
 FCFAConvert[CreateFeynAmp[gggg, PreFactor -> 1], 
  IncomingMomenta -> {p1, p2, p3, p4}, DropSumOver -> True, 
  SUNIndexNames -> {a, b, c, d, e}, 
  LorentzIndexNames -> {Subscript[\[Mu], 1], Subscript[\[Mu], 2], 
    Subscript[\[Mu], 3], Subscript[\[Mu], 4], Subscript[\[Mu], 5], 
    Subscript[\[Mu], 6]}]
```

the first amplitude comes up with a factor -f^($AL$14645cd) f^(ab$AL$14645)-f^($AL$14646bd) f^(ac$AL$14646) . Although the expression itself seems to be valid, the label $AL$(some number) is very odd.

**Comment by vsht** [comment]
Those are just dummy indices, so I don't really understand what is the problem here..

**Comment by DexKim** [comment]
I was wondering if those dummy indices could be given names that would be more familiar to the human eye. I thing I should just live with it...
