### ISSUE TITLE
Problem with PaVeUVPart[] in some special cases

### ISSUE THREAD

**Issue by HBelusca** [FeynCalc/feyncalc#34]
*  <summary>Your Mathematica version</summary>    

  ```11.2.0 for Microsoft Windows (64-bit) (September 11, 2017)```

*  <summary>Your FeynCalc version</summary>    

  ```9.3.0 (development)```

*  <summary>Did you try to reinstall FeynCalc (stable version) using the automatic installer to make sure that you have the latest bugfixes?</summary>    

  ```Latest development HEAD repository```

---

I am computing UV divergent parts of some amplitudes expressed in terms of Passarino-Veltman 1-loop functions, using the FeynCalc function `PaVeUVPart[]`, and noticed that the returned results did not agree with the ones obtained through FeynCalc/Package-X `PaXEvaluate[]` or through FormCalc:

```mathematica
In[1]:= $LoadAddOns = {"FeynHelpers"};
In[2]:= << FeynCalc`

In[3]:= myAmp = B0[p12, 0, 0];

In[4]:= Simplify@Normal@Series[Simplify@PaVeUVPart[myAmp] /. {D -> 4 - 2 Epsilon}, {Epsilon, 0, 0}]
Out[4]= 1/Epsilon

In[5]:= Expand@PaXEvaluate[myAmp]
Out[5]= 1/Epsilon + Log[-(Mu^2/(\[Pi] p12))] - Gamma + 2
```
which is OK, as well as:

```mathematica
In[6]:= myAmp = PaVe[0, 0, {0, p12, p12}, {0, 0, 0}]; (** C00 function **)

In[7]:= Simplify@Normal@Series[Simplify@PaVeUVPart[myAmp] /. {D -> 4 - 2 Epsilon}, {Epsilon, 0, 0}]
Out[7]= 1/(4 Epsilon)

In[8]:= Expand@PaXEvaluate[myAmp]
Out[8]= 1/(4 Epsilon) + 1/4 Log[-Mu^2/(\[Pi] p12)] - Gamma/4 + 1/2
```

However:

```mathematica
In[6]:= myAmp = C0[0, p12, p12, 0, 0, 0];

In[7]:= Simplify@Normal@Series[Simplify@PaVeUVPart[myAmp] /. {D -> 4 - 2 Epsilon}, {Epsilon, 0, 0}]
Out[7]= 0

In[8]:= Expand@PaXEvaluate[myAmp]
Out[8]= -1/(Epsilon p12) - Log[-(\[Pi] Mu^2)/p12]/p12 + Gamma/p12 + 2 Log[\[Pi]]/p12
```
is **NOT** OK (PaX gives the correct result however).

Similar problem also appear for D0 functions, for example with: `D0[0, p12, 0, p12, p12, p12, 0, 0, 0, 0]` (PaX returns `-2/(Epsilon p12^2)` for the div-part, while PaVeUVPart[] returns 0).

This problem happens because the massless case of C0 and D0 (and possibly their families Cij, Dijkl etc...) is singular; this can be seen when evaluating these functions by hand using Feynman parametrization: one needs to keep the full D-dimensional dependence for the powers of the Feynman parameters, which, after integration, turn into a product of Gamma functions that depend on D. Then, by expanding over `Epsilon = (4-D)/2`, one obtains the `1/Epsilon` poles as expected.

**Comment by HBelusca** [comment]
Thank you very much for your explanation and for the references!
So I now understand what happened: I was actually seeing the IR divergence that was generated due to the fact the mass parameters were set to zero in the loop integrals.

I thus think we can close this (non-)issue report.

**Comment by vsht** [comment]
You are welcome. It might be actually interesting to introduce something like `IRDivergentQ` returning `True` or `False` to check whether the given PaVe function contains soft or collinear singularities. This is actually quite easy at 1-loop as we only need to extract the modified Cayley matrix of the integral and check whether it's determinant is zero or not. I will think about this.
