### ISSUE TITLE
"Solution to the system of linear equations is incorrect" error when computing tensor reduction with Tdec

### ISSUE THREAD

**Issue by HBelusca** [FeynCalc/feyncalc#37]
*  <summary>Your Mathematica version</summary>

```8.0.4.0 for Microsoft Windows (64-bit) (2011)```
```11.2.0 for Microsoft Windows (64-bit) (September 11, 2017)```

*  <summary>Your FeynCalc version</summary>

```9.3.0 (development) (d953b1aae71d54cd834f386ca4584cb515f2652c)```

---

When performing 2-loop calculations, a tensor reduction is performed on an (Lorentz-index uncontracted) expression, and in fine the following Tdec command is executed:

```Tdec[{{q1, $3050}, {q1, $3489}, {q2, $3047}, {q2, $3488}} , {k1}, Dimension -> D, List -> False, UseTIDL -> False]```

This line fails with the following error:
```Tdec::failmsg: Error! TID has encountered a fatal problem and must abort the computation. The problem reads: The solution to the system of linear equations is incorrect.```

However, running instead:

```Tdec[{{q1, mu}, {q1, nu}, {q2, rho}, {q2, sig}} , {k1}, Dimension -> D, List -> False, UseTIDL -> False]```

or even:

```Tdec[{{q1, $3050}, {q1, $3489}, {q2, $3047}, {q2, mu}} , {k1}, Dimension -> D, List -> False, UseTIDL -> False]```

works perfectly!

The problem seems to be related with the "format" of the Lorentz indices used in the momenta list in the Tdec call (the dollar-variables).

**Comment by vsht** [comment]
Nice. Now the symmetrizer should hopefully always generate a proper permutation group to prevent
such issues.

**Comment by HBelusca** [comment]
Confirmed fixed, thank you very much!
