### ISSUE TITLE
AntiSymmetrize

### ISSUE THREAD

**Issue by whit2333** [FeynCalc/feyncalc#4]
AntiSymmetrize is no longer found. Also, there is a Symmetrize function in the Mathematica core language now. When I load my old version of feyncalc AntiSymmetrize works.

**Comment by vsht** [comment]
AntiSymmetrize and Symmetrize are now called FCAntiSymmetrize and FCSymmetrize. Exactly because there is a now Symmetrize function in the Mathematica core language.

**Comment by whit2333** [comment]
Thanks! The link to the draft documentation in the wiki needs updated with this. I'd gladly make this correction if you could point me towards the source of the doc. Does it have separate repo?

**Comment by vsht** [comment]
The draft documentation is unfortunately not very much up to date. The built in documentation of the package (provided through the documentation center) is a bit more recent.

The documentation repo is here:
https://github.com/FeynCalc/fcguide

I've updated it just now for FCSymmetrize/FCAntiSymmetrize.
