### ISSUE TITLE
Polarization not compatible with Calc

### ISSUE THREAD

**Issue by ChiMaoShuPhy** [FeynCalc/feyncalc#41]
*  <summary>Your Mathematica version</summary>    

  ```11.0.1 for Mac OS X x86 (64-bit) (September 21, 2016)```

*  <summary>Your FeynCalc version</summary>    

  ```9.2.0```

*  <summary>Did you try to reinstall FeynCalc (stable version) using the automatic installer to make sure that you have the latest bugfixes?</summary>    

  ```Yes```

*  <summary>Please provide a minimal working example that illustrates the problem. Please explain the difference between the current behavior and the expected behavior.</summary>    

  Without setting ```Transversality -> True```, ```Pair[Momentum[k + P], Momentum[Polarization[k + P, I]]] // Calc``` returns ```0```. However, inputs like ```Pair[Momentum[k +2 P], Momentum[Polarization[k +2 P, I]]]``` return nonzero results as expected.

**Comment by vsht** [comment]
Thanks, should be now fixed.

**Comment by ChiMaoShuPhy** [comment]
Many thanks! I just tested and now it works as expected.
