### ISSUE TITLE
DoPolarizationSums documentation is outdated

### ISSUE THREAD

**Issue by magv** [FeynCalc/feyncalc#44]
Hi. Is it possible to correct the documentation on DoPolarizationSums at [1] (that is, `Documentation/English/ReferencePages/Symbols/DoPolarizationSums.nb`)? The syntax it lists has not been valid for years. I've found the explanation for the new syntax at [2]. The help message for DoPolarizationSums seems to be correct too -- just using that would be an improvement.

[1] https://feyncalc.github.io/FeynCalcBook/ref/DoPolarizationSums.html
[2] http://www.feyncalc.org/forum/0844.html

**Comment by vsht** [comment]
Yeah, the documentation is indeed outdated in many places. I'm currently working on an updated version
that should accompany the release of FeynCalc 9.3. Since that version features a lot of new stuff (especially
Cartesian tensors and very generic propagators), an up-to-date documentation is essential.

The preliminary changelog is already available
https://github.com/FeynCalc/feyncalc/blob/master/FeynCalc/Changelog.md
and I hope to finish updating the documentation withing several weeks.

The general program with the documentation is that Wolfram Workbench does not support updating single pages only. Instead, you always have to rebuild the whole thing (~ 30 min per run) and since that changes the CellIDs in the notebooks, each rebuild generated a lot of noise in the git repo. So I tend to accumulate some amount of changes before rolling out a new version of the documentation.

If you have noticed more glitches or pages that are badly outdated, feel free to list them here. This would make it easier for me to improve the things.

**Comment by magv** [comment]
Wolfram Workbench sounds like a mess. On the other hand I half expected .nb to be a binary format, so the fact that it's textual at all is already something.

I haven't gone through all the documentation, but from a quick glance:

1. https://feyncalc.github.io/FeynCalcBook/ref/ScalarProduct.html
says that `ScalarProduct[a,b] = m2`, among other things, sets `Pair[Momentum[a,___],Momentum[b,___]]` to `m2`, but it actually only sets `Pair[Momentum[a,X],
Momentum[b,X]]`, where `X` is taken from the `SetDimensions` option,
`{4, D}` by default.

2. https://feyncalc.github.io/FeynCalcBook/ref/FCFAConvert.html
is referenced from the index, but is in fact missing.

3. There's no documentation for the fairly useful
`FCCanonicalizeDummyIndices`.

(I'll add more if I'll run into a notable problem).

**Comment by magv** [comment]
Here's the full list of broken links in the documentation index:

https://feyncalc.github.io/FeynCalcBook/ref/FAPatch.html
https://feyncalc.github.io/FeynCalcBook/ref/FCFAConvert.html
https://feyncalc.github.io/FeynCalcBook/ref/FCPrepareFAAmp.html
https://feyncalc.github.io/FeynCalcBook/ref/QCDFeynmanRuleConvention.html
https://feyncalc.github.io/FeynCalcBook/ref/PaveOrder.html
https://feyncalc.github.io/FeynCalcBook/ref/PaVeReduce.html
https://feyncalc.github.io/FeynCalcBook/ref/TFIOrder.html
https://feyncalc.github.io/FeynCalcBook/ref/ToPaVe.html
https://feyncalc.github.io/FeynCalcBook/ref/StringChomp.html
https://feyncalc.github.io/FeynCalcBook/ref/FCLoopBasisIncompleteQ.html
https://feyncalc.github.io/FeynCalcBook/ref/FCLoopBasisOverdeterminedQ.html
https://feyncalc.github.io/FeynCalcBook/ref/FCLoopBasisFindCompletion.html
https://feyncalc.github.io/FeynCalcBook/ref/FCLoopCanonicalize.html
https://feyncalc.github.io/FeynCalcBook/ref/FCLoopSolutionList.html
https://feyncalc.github.io/FeynCalcBook/ref/FCLoopSplit.html
https://feyncalc.github.io/FeynCalcBook/ref/GenPaVe.html
https://feyncalc.github.io/FeynCalcBook/ref/FCRenameDummyIndices.html
https://feyncalc.github.io/FeynCalcBook/ref/Complement1.html
https://feyncalc.github.io/FeynCalcBook/ref/FCF.html
https://feyncalc.github.io/FeynCalcBook/ref/FCSplit.html
https://feyncalc.github.io/FeynCalcBook/ref/SDF.html
https://feyncalc.github.io/FeynCalcBook/ref/SUNFDelta.html
https://feyncalc.github.io/FeynCalcBook/ref/SPE.html
https://feyncalc.github.io/FeynCalcBook/ref/SUNTF.html
https://feyncalc.github.io/FeynCalcBook/ref/ExplicitSUNFIndex.html
https://feyncalc.github.io/FeynCalcBook/ref/SUNFIndex.html
https://feyncalc.github.io/FeynCalcBook/ref/FVE.html
https://feyncalc.github.io/FeynCalcBook/ref/AlphaStrong.html
https://feyncalc.github.io/FeynCalcBook/ref/AlphaFS.html
https://feyncalc.github.io/FeynCalcBook/ref/GAE.html
https://feyncalc.github.io/FeynCalcBook/ref/GSE.html

Also, the link for SUNFDeltaContract actually shows https://feyncalc.github.io/FeynCalcBook/ref/SUNDeltaContract.html (there's no page for SUNFDeltaContract).

**Comment by vsht** [comment]
Yikes, this is indeed far from being acceptable. I've already prepared the documentation for `FCLoop*` and
some other functions from your list, but there is still much work remaining to be done. Thanks, this should 
be definitely fixed until the new version is released!

**Comment by vsht** [comment]
Ok, I went through your list and added all missing pages to DocSource. I guess it will still take me some time to polish the texts a bit, add cross references and rebuild the whole thing, but at least the docs should
be almost complete then. Thanks for your help!

**Comment by vsht** [comment]
I've rebuilt the documentation for the development version, where all the missing pages have been added.
The online version will be updated when FeynCalc 9.3 is released, which should be within 1-2 months.

**Comment by vsht** [comment]
Feel free to reopen this issue if you still spot problems. At least I believe that I've checked that all help pages open properly and the code there evaluates correctly.
