### ISSUE TITLE
Incorrect substitution within `DiracSimplify`

### ISSUE THREAD

**Issue by JP-Ellis** [FeynCalc/feyncalc#49]
The output of `DiracSimplify` appears to replace certain patterns in its input.  I have a trivial example below showing the issue.  I don't know if `i` is the only culprit though.

```mathematica
DiracSimplify[SpinorU[p[i], m[i]]]
```
produces 
> ```mathematica
> Spinor[Momentum[p[2]], m[2], 1]
> ```
which is incorrect (the simplification is trivial), and it should instead be returning:
> ```mathematica
> Spinor[Momentum[p[i]], m[i], 1]
> ```

----

|  |  |
| --- | --- |
| Mathematica Version | 12.0.0 for Linux x86 (64-bit) (April 7, 2019) |
| FeynCalc Version | Latest commit on master as of writing this issue |

**Comment by vsht** [comment]
Does your minimal example work on a fresh kernel? I've just tried to reproduce it (also switching to the latest master commit on GitHub) but got only `Spinor[Momentum[p[i]], m[i], 1]` as expected.

![Bildschirmfoto vom 2019-10-08 12-53-41](https://user-images.githubusercontent.com/7283188/66390449-fa173000-e9ca-11e9-85f9-3e7d920e940c.png)

**Comment by JP-Ellis** [comment]
Yes, using a fresh kernel:

![image](https://user-images.githubusercontent.com/3196162/66391921-20b08780-ea1a-11e9-9a78-5e5905b269eb.png)

This is strange that you can't reproduce it...

**Comment by vsht** [comment]
No problem, glad you figured it out.
