### ISSUE TITLE
Bug in FCMultiLoopTID: Mismatch between pure-evanescent or 4D structures, vs. fully d-D structures

### ISSUE THREAD

**Issue by HBelusca** [FeynCalc/feyncalc#52]
*  <summary>Your Mathematica version</summary>    

```11.3.0 for Microsoft Windows (64-bit) (March 7, 2018)```

*  <summary>Your FeynCalc version</summary>    

```9.4.0 master (a3aab44faccb7e68d0fab29a626b1ddc47667725)```

*  <summary>Did you try to reinstall FeynCalc (stable version) using the automatic installer to make sure that you have the latest bugfixes?</summary>    

```Using git master repo checkout```

---

Using FCMultiLoopTID[] returns unexpected results when the provided amplitude contains explicit evanescent (in D-4 dimensions) or 4-dimensional structures. This causes problems in analytical calculation of (2+) loop amplitudes in e.g. BMHV scheme.
This problem also shows up, at 1-loop level, when comparing the tensor reduction obtained via the usual TID[] function, and by FCMultiLoopTID[] with 1 momentum specification.

The observed effect is that it appears, that somehow FCMultiLoopTID[] "replaces" all occurrences of loop momenta (when evanescent or 4-dimensional projections of these are present) to their fully d-dimensional counterparts.
See the attached notebook (in zip archive) for explicit examples, as well as for a "workaround".

[FeynCalc_bug_FCMultiLoopTID.zip](https://github.com/FeynCalc/feyncalc/files/4759327/FeynCalc_bug_FCMultiLoopTID.zip)

**Comment by vsht** [comment]
Should be also taken care of. 
The alternative you were experimenting with can produce tensor integrals with identical indices, as in 
the case of SPE[q1,q1]. Actually, now I see why I had the corresponding warning in Tdec

Things like `Tdec[{{l, mu1}, {l, mu1}, {l, mu3}}, {p}]` do not work correctly. It is much simpler to
calculate `Tdec[{{l, mu1}, {l, mu2}, {l, mu3}}, {p}]` and contract with`g^{mu nu}` afterwards.

**Comment by vsht** [comment]
Since there seem to be no further issues related to the fix, I'm closing this bug.
