### ISSUE TITLE
Fix FourDivergence (and ThreeDivergence) to handle derivatives in different dimensions

### ISSUE THREAD

**Issue by vsht** [FeynCalc/feyncalc#69]
Currently `FourDivergence` claims that a derivative of a 4-dim vector w.r.t to a D-dim vector is zero.
This is not really consistent as one can see in the following example

```
FourDivergence[FV[p, mu], FVD[p, nu]]
FourDivergence[FVD[p, al] MT[al, mu], FVD[p, nu]]
```

```
FourDivergence[FVD[p, mu], FV[p, nu]]
FourDivergence[FVD[p, mu], FVD[p, al]] MT[al, nu] // Contract
```

Likewise for Dirac matrices, propagators and tensors. This should be fixed.

**Comment by vsht** [comment]
@duartefontes Could you please have a look and test if it works for you? I think that as of now FeynMaster is the only tool that needs/uses four derivative in the t'Hooft-Veltman scheme. 

```
FCSetDiracGammaScheme["BMHV"];
FourDivergence[FVD[p, mu], FV[p, nu]]
```

**Comment by duartefontes** [comment]
Hi, Vlad,
I see that it no longer gives warnings; yet, FeynMaster uses by default NDR. I have played around a bit with other schemes, but I have almost no experience.

**Comment by vsht** [comment]
I see. I just noticed that FeynMaster has a dedicated derivative routine for such cases, since FourDivergence
could not handle those properly. So I thought that it was needed for some calculations done by FeynMaster.

**Comment by HBelusca** [comment]
Oh nice! A feature that was necessary!
