### ISSUE TITLE
Cannot Load FeynCalc

### ISSUE THREAD

**Issue by gabilicht** [FeynCalc/feyncalc#7]
I have installed FeynCalc 8.2 in Mathematica 10. But I keep receiving  error messages when I try to load the programme. 
![feyncalc](https://cloud.githubusercontent.com/assets/18708699/14869148/0926c1c2-0ca8-11e6-9f38-bcd9896c7019.png)

**Comment by vsht** [comment]
There seems to be some interference between the FeynCalc 9 (from the automatic installer) and FeynCalc 8.2 that I don't quite understand.

Could you please delete both `FeynCalc` and `HighEnergyPhysics` directories from `/home/gabi/.Mathematica/Applications` and then run the automatic installer again?

**Comment by vsht** [comment]
Since there were no further replies from @gabilicht, I'm closing the issue now.
