### ISSUE TITLE
"Cannot open FeynCalc" error message

### ISSUE THREAD

**Issue by rmastand** [FeynCalc/feyncalc#80]
Using Mathematica version 11.3.0 for Mac OS X x86 (64-bit) (March 7, 2018), trying to install the newest version of FeynCalc. I have tried to install Feyncalc in two different ways, using the automatic installation and manual installation methods documented [here](https://github.com/FeynCalc/feyncalc/wiki/Installation). Both times, the installation appears to run to completion without errors, but running the command `<< FeynCalc` leads to the error message "Cannot open FeynCalc". I am not sure if I'm missing some dependencies or haven't linked the package properly; any help would be greatly appreciated!

**Comment by vsht** [comment]
At first just a very simple question: You do write
```
<<FeynCalc`
```
**with the back tick** at the end, right?

**Comment by vsht** [comment]
In view of the lacking feedback I suppose that the issue is now solved, otherwise feel free to reopen.
