### ISSUE TITLE
Problem with the function DoPolarizationSums

### ISSUE THREAD

**Issue by Mantani** [FeynCalc/feyncalc#9]
Hi, I'm a beginner in the use of FeynCalc. I'm trying to compute basic amplitude but i'm having problem when i face the vector polarization sum. I'm using Mathematica 10 and FeynCalc 9.0.1. Here an example of the problem:

In[2]:= expr = 
  PolarizationVector[k, \[Mu]] PolarizationVector[k, \[Nu]];

In[3]:= expr

Out[3]= Pair[LorentzIndex[\[Mu]], Momentum[Polarization[k, I]]] Pair[
  LorentzIndex[\[Nu]], Momentum[Polarization[k, I]]]

In[4]:= DoPolarizationSums[expr, k, n]

Out[4]= Pair[LorentzIndex[\[Mu]], Momentum[Polarization[k, I]]] Pair[
  LorentzIndex[\[Nu]], Momentum[Polarization[k, I]]]

As you can see DoPolarizationSums does nothing at all and i don't know what i'm doing wrong. 
Thanks for the help,
Luca Mantani

**Comment by vsht** [comment]
Ciao Luca, 

first of all, in Mathematica (unlike FORM) you cannot use variables enclosed in square brackets, so [Mu] or [Nu] is incorrect syntax.

Then, to sum over polarizations (according to the usual definition), one vector must be complex conjugate of the other. So the correct code reads:

```
SP[k,k]=0;
expr = PolarizationVector[k, mu, 
   Transversality -> True] ComplexConjugate[
   PolarizationVector[k, nu, Transversality -> True]]
DoPolarizationSums[expr, k, n]
```

Without `SP[k,k]=0;` you will get a warning about using polarization sum for massless vector bosons, without putting the boson on-shell.

PS Have a look at the sample calculations in the Examples directory inside FeynCalc.This should help you to get some experience with the package.

**Comment by Mantani** [comment]
Thank you very much! Now it works but i've got a doubt left. What is n exactly? What is the difference if i put 0 instead of n?

**Comment by Mantani** [comment]
I have another issue. The following code doesn't work:
```
In[33]:= expr = 
 PolarizationVector[k, mu]] ComplexConjugate[
   PolarizationVector[k, nu]]]

Out[33]= Pair[LorentzIndex[mu]], Momentum[Polarization[k, I]]] Pair[
  LorentzIndex[nu]], Momentum[Polarization[k, -I]]]

In[36]:= expr = Contract[MT[mu, nu] expr]

Out[36]= Pair[Momentum[Polarization[k, -I]], 
 Momentum[Polarization[k, I]]]

In[37]:= DoPolarizationSums[expr, k, 0]

Out[37]= Pair[Momentum[Polarization[k, -I]], 
 Momentum[Polarization[k, I]]]


```
I expected that the result would be -4. 

If i write the following code instead, i get what i expect:
```
In[39]:= expr = Contract[
 PolarizationVector[k, mu] Pair[Momentum[p], 
   LorentzIndex[mu]] ComplexConjugate[
   PolarizationVector[k, nu]] Pair[Momentum[q], 
   LorentzIndex[nu]]]

Out[39]= Pair[Momentum[p], Momentum[Polarization[k, I]]] Pair[
  Momentum[q], Momentum[Polarization[k, -I]]]

In[40]:= DoPolarizationSums[expr, k, 0]

Out[40]= -Pair[Momentum[p], Momentum[q]]
```
Why it doesn't work if two polarization vectors are contracted?

Thanks in advance for the help,
Luca Mantani

**Comment by vsht** [comment]
This is indeed a bug, that was introduced after fixing issue #8
The stable version is not affected, only the development one.
Should be now fixed, thanks.

Concerning your question about n. n is an auxiliary
vector that is required when you compute polarization
sum for massless vector bosons. A massless vector boson
has only two physical polarizations, so together with its 
momentum you have 3 4-vectors to your disposal. But 3 vectors
are not enough to completely span a 4D vector space.

So to write down a Lorentz covariant expression for
the polarization sum you need an auxiliary vector n^mu that must not be a linear combination
of the above mentioned 3 vectors.

This way one can derive the polarization sum formula used in FeynCalc. It can be found e.g. in
in M. Boehm, A. Denner and H. Joos, Gauge Theories of the Strong and Electroweak Interaction,
Eq. A.1.45 and Eq. A.1.46. This formula ensures that when computing polarization sums we are summing only over physical polarizations.

Gauge invariance warranties that the final result is independent on the choice of n^mu (as long as
n^mu satisfies certain conditions), although sometimes one needs to go into single components of 
4-vectors to see this explicitly. In fact,  in QED guage invariance is so "strong" that one 
can use just -g^{mu nu} for the polarization sum (this is what FeynCalc does when you put n=0), 
without worrying about the extra terms.  In QCD, however, this is not the case and there we 
need the full formula. See e.g. chapters 5.5  and 16.1 in Peskin or in your favourite QFT pheno book.

**Comment by Mantani** [comment]
Great, thank you for the help!
