### ISSUE TITLE
FCFA uses PropagatorDenominator as a stand-alone

### ISSUE THREAD

**Issue by vollous** [FeynCalc/feyncalc#93]
*  <summary>Your Mathematica version</summary>    

  ```12.1.1```

*  <summary>Your FeynCalc version</summary>    

  ```9.3.1```

*  <summary>Did you try to reinstall FeynCalc (stable version) using the automatic installer to make sure that you have the latest bugfixes?</summary>    

  ```Yes```

*  <summary>Does your Mathematica initialization file contain statements that might influence the behavior of FeynCalc? Sometimes external packages may modify `init.m` in unusual ways, causing troubles for other codes.</summary>    
```
$LoadAddOns = {"FeynArts"};
<< FeynCalc`
$FAVerbose = 0;
``` 
and `SetOptions[FourVector, FeynCalcInternal -> False];`

I am working on an extension of the standard model. My model was designed in FeynRules and now I am using FeynCalc  patched with FeynArts. I have an additional complex field that couples with the Higgs.

Here is one of the diagrams.

![image](https://user-images.githubusercontent.com/57032457/103537592-93fab080-4e8c-11eb-9dce-0095bb051d4d.png)

When I generate the ampltide with:

```
decay = InsertFields[oneloop, S[1] -> {S[5], S[5]}, 
   InsertionLevel -> {Particles}, 
   Model -> NotebookDirectory[] <> "SMH2DM_FA/SMH2DM_FA", 
   GenericModel -> NotebookDirectory[] <> "SMH2DM_FA/SMH2DM_FA"];
FCFAConvert[CreateFeynAmp[decay], IncomingMomenta -> {p}, 
  OutgoingMomenta -> {k1, k2}, List -> True, LoopMomenta -> {q}, 
  ChangeDimension -> D];
```

 I get these terms:

`(...) PropagatorDenominator(k1+k2-q,MH Sqrt[Subscript[\[Xi], S(Gen5)]])`
After consulting the documentation I found that the PropagatorDenominator need to be used with `FeynAmpDenominator`

And because of this I cant convert the amplitudes to the Passarino Veltman basis.

An additional note that might be important. When I calculate the amplitudes with just FeynArts I dont get the `Subscript[\[Xi]` term. The amplitude is something like:
`(...) PropagatorDenominator(k1+k2-q,MH)`

Thank you for the help!

**Comment by vsht** [comment]
Most likely you forgot to patch the model
```
FAPatch[PatchModelsOnly -> True]
```

**Comment by vollous** [comment]
Hi, still not working.

Only by running `CreateFeynAmp[decay]` I get

`FAFeynAmp(GraphID(Topology==1,Generic==1,Particles==1,Number==1),Integral[q1], (...) PropagatorDenominator(k1+k2-(q1),MH Sqrt[Subscript[\[Xi], S(Gen5)]]))`

With no `FeynAmpDenominator` attached to it.

I checked and I have the same version of `FeynArts` in the stand-alone package and in the patched package (FeynCalc)

**Comment by vsht** [comment]
If the model is located not in FeynArts/Models, FAPatch needs to have the full directory path

```
FAPatch[PatchModelsOnly -> True, 
 FAModelsDirectory -> 
  FileNameJoin[{NotebookDirectory[], "MyModelDir"}]]
```

Upon patching, the output of CreateFeynAmp should not contain any `PropagatorDenominator` symbols, only
`FAPropagatorDenominator` may appear instead. So in your case it seems that the model still didn't get patched
correctly.

**Comment by vollous** [comment]
That did the trick! 
Thank you!
